# Generated by Django 4.1.7 on 2023-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_age_alter_userprofile_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bmi',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bmr',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='energy_intake',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
