# Generated by Django 4.1.7 on 2023-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_age_alter_userprofile_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
