# Generated by Django 4.1.7 on 2023-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='yob',
            field=models.IntegerField(default=1994),
        ),
    ]
