# Generated by Django 4.1.7 on 2023-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userprofile_age_alter_userprofile_bmi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friday', models.ManyToManyField(related_name='Friday_NP_set', to='api.meal')),
                ('Mondey', models.ManyToManyField(related_name='Mondey_NP_set', to='api.meal')),
                ('Saturday', models.ManyToManyField(related_name='Saturday_NP_set', to='api.meal')),
                ('Sunday', models.ManyToManyField(related_name='Sunday_NP_set', to='api.meal')),
                ('Thursday', models.ManyToManyField(related_name='Thursday_NP_set', to='api.meal')),
                ('Tuesday', models.ManyToManyField(related_name='Tuesday_NP_set', to='api.meal')),
                ('Wednesday', models.ManyToManyField(related_name='Wednesday_NP_set', to='api.meal')),
            ],
        ),
    ]
