# Generated by Django 4.1.7 on 2023-03-21 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Next', 'Next')], max_length=20)),
                ('day', models.CharField(choices=[('Mondey', 'Mondey'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('meal_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal1_Cal_set', to='api.meal')),
                ('meal_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal2_Cal_set', to='api.meal')),
                ('meal_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal3_Cal_set', to='api.meal')),
                ('meal_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal4_Cal_set', to='api.meal')),
                ('meal_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal5_Cal_set', to='api.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
