# Generated by Django 4.1.7 on 2023-04-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_calendar_delete_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='field1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='field2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='field3',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
