# Generated by Django 4.1.7 on 2023-04-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_meal_field1_meal_field2_meal_field3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='dish_1',
        ),
    ]
