# Generated by Django 4.1.7 on 2023-04-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_meal_dish_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_10',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_2',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_3',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_4',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_5',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_6',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_7',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_8',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dish_9',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='morocco',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='spain',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='turkey',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='type',
        ),
    ]
