# Generated by Django 4.1.7 on 2023-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_meal_description_remove_meal_dish_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
