# Generated by Django 4.1.7 on 2023-04-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_dish_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='country',
            field=models.CharField(choices=[('Greece', 'Greece'), ('Spain', 'Spain'), ('Moroco', 'Morocco'), ('Turkey', 'Turkey')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='name_gr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Morning_snack', 'Morning Snack'), ('Lunch', 'Lunch'), ('Afternoon_snack', 'Afternoon Snack'), ('Dinner', 'Dinner')], max_length=20, null=True),
        ),
    ]
