# Generated by Django 4.1.7 on 2023-04-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_meal_autumn_meal_spring_meal_summer_meal_winter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dish_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish1_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish10_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish2_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish3_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish4_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish5_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish6_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish7_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish8_menu_set', to='api.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dish_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish9_menu_set', to='api.dish'),
        ),
    ]
