# Generated by Django 4.1.7 on 2023-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_meal_dish_1_meal_dish_10_meal_dish_2_meal_dish_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='autumn',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='carbohydrates',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='cereals',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='cooked_vegetables',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='diary',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='eggs',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='fish',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='fruit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_adult_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_adult_gr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_child_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_child_gr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='kcal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_gr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='nuts',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='pasta',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='pork',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='pulses',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='raw_vegetables',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_gr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='red_meat',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='rice',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='soups',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='spring',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='summer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='tip_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='tip_gr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='tubers',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Side', 'Side'), ('Bread', 'Bread'), ('Fruit', 'Fruit'), ('Unique', 'Unique'), ('Semi', 'Semi'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast'), ('Morning snack', 'Morning Snack'), ('Afternoon snack', 'Afternoon Snack')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='white_meat',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='winter',
            field=models.BooleanField(null=True),
        ),
    ]
