# Generated by Django 4.1.7 on 2023-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_meal_country_alter_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='ingredients_adult_gr',
            new_name='ingredients_adult_m',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='ingredients_child_en',
            new_name='ingredients_child_1_en',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='ingredients_child_gr',
            new_name='ingredients_child_1_m',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='name_gr',
            new_name='ingredients_child_2_en',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='recipe_gr',
            new_name='ingredients_child_2_m',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='tip_gr',
            new_name='ingredients_child_3_en',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='name_gr',
            new_name='name_m',
        ),
        migrations.AddField(
            model_name='dish',
            name='for_proposals',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='for_school',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='green',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_child_3_m',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_child_4_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_child_4_m',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='multicolor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_m',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='no_color',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein_mix',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='purple',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_m',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='red',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='semi_unique',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='tip_m',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='unique',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='vegetables_semi',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='white',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='yellow',
            field=models.BooleanField(null=True),
        ),
    ]
