# Generated by Django 4.1.7 on 2023-05-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_ingredients_adult_gr_dish_ingredients_adult_m_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cousine',
            new_name='country',
        ),
    ]
