# Generated by Django 4.1.7 on 2023-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carbohydrates',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='cooked_vegetables',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='kcal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='nuts',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='raw_vegetables',
            field=models.IntegerField(null=True),
        ),
    ]
