# Generated by Django 4.1.7 on 2023-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_meal_carbohydrates_meal_cooked_vegetables_meal_fat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='nuts',
        ),
        migrations.AddField(
            model_name='meal',
            name='fruit',
            field=models.IntegerField(null=True),
        ),
    ]
