# Generated by Django 4.1.7 on 2023-05-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_meal_nuts_meal_fruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='cooked_vegetables',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='kcal',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='raw_vegetables',
        ),
    ]
