# Generated by Django 4.2.2 on 2023-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_dish_ingredients_adult_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_language',
            name='language',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='meal_language',
            name='language',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
