# Generated by Django 4.2.2 on 2023-06-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_dish_language_language_meal_language_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_language',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meal_language',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
