# Generated by Django 4.2.2 on 2023-06-08 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_alter_dish_language_id_alter_meal_language_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('yob', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('pal', models.CharField(max_length=50)),
                ('halal', models.BooleanField()),
                ('diary', models.BooleanField()),
                ('eggs', models.BooleanField()),
                ('fish', models.BooleanField()),
                ('country', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
