# Generated by Django 4.2.2 on 2023-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_userprofilehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilehistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
