# Generated by Django 4.2.2 on 2023-06-08 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_alter_userprofilehistory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateTimeField()),
                ('day', models.IntegerField()),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofilehistory',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='userprofilehistory',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='NPmeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.IntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meal')),
                ('np', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.np')),
            ],
            options={
                'ordering': ['meal_number'],
            },
        ),
        migrations.AddField(
            model_name='np',
            name='meals',
            field=models.ManyToManyField(through='api.NPmeal', to='api.meal'),
        ),
        migrations.AddField(
            model_name='np',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
