# Generated by Django 4.2.2 on 2023-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_np_alter_userprofilehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='np',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='np',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
