# Generated by Django 4.2.2 on 2023-06-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_np_start_date_alter_np_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='np',
            name='week',
        ),
    ]
