# Generated by Django 4.2.2 on 2023-06-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_np_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='np',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
