# Generated by Django 4.2.2 on 2023-06-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_np_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='np',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
