# Generated by Django 4.2.2 on 2023-07-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_userprofile_nuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilehistory',
            name='nuts',
            field=models.BooleanField(null=True),
        ),
    ]
