# Generated by Django 4.2.2 on 2023-07-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_dish_language_ingredients_child_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='for_proposals',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='for_school',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='type',
        ),
    ]
