# Generated by Django 4.2.2 on 2023-07-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
